spring.application.name=Kurio-Backend
server.port=8080

spring.mongodb.uri=mongodb://localhost:27017/kurio

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/kurio-6ecc0
spring.security.oauth2.resourceserver.jwt.audiences=kurio-6ecc0