spring.application.name=Kurio-Backend
server.port=8080

spring.mongodb.uri=mongodb://mongo:27017/kurio_db

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/kurio-6ecc0
spring.security.oauth2.resourceserver.jwt.audiences=kurio-6ecc0
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB